config/routes.rb
Rails.application.routes.draw do
  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  
}
devise_scope :user do
  post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
end
 devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


root to: "public/homes#top"
get 'about' => 'public/homes#about'

###public###

#サウナ情報
get '/public/saunas' => 'public/saunas#index' 
get '/public/saunas/:id/map' => 'public/saunas#map', as: :public_saunas_map
get '/public/saunas/search' => 'public/saunas#search', as: :public_saunas_search
get '/public/saunas/result' => 'public/saunas#result', as: :public_saunas_result
get '/public/saunas/:id' => 'public/saunas#show', as: :public_saunas_show

#レビュー
get '/public/saunas/:sauna_id/reviews' => 'public/reviews#index', as: :public_sauna_reviews
get '/public/saunas/:sauna_id/reviews/new' => 'public/reviews#new', as: :new_public_sauna_review
post '/public/saunas/:sauna_id/reviews' => 'public/reviews#create', as: :public_sauna_reviews_create
get '/public/saunas/:sauna_id/reviews/:id/edit' => 'public/reviews#edit', as: :edit_public_sauna_review
patch '/public/saunas/:sauna_id/reviews/:id' => 'public/reviews#update', as: :public_sauna_review_update
delete '/public/saunas/:sauna_id/reviews/:id' => 'public/reviews#destroy', as: :public_sauna_review_destroy

#コメント
post '/public/:review_id/comments' => 'public/comments#create', as: :public_comments_create
get '/public/:review_id/comments/:id' => 'public/comments#show', as: :public_comments_show
get '/public/:review_id/comments/:id/edit' => 'public/comments#edit', as: :public_comments_edit
get '/public/:review_id/comments/' => 'public/comments#reload'
patch '/public/:review_id/comments/:id' => 'public/comments#update', as: :public_comments_update
delete '/public/:review_id/comments/:id' => 'public/comments#destroy',as: :public_comments_destroy




#マイページ
delete '/public/users/destroy' => 'public/users#destroy'
get '/public/users/my_page' => 'public/users#show'
get '/public/users/infomation/edit' => 'public/users#edit'
patch '/public/users/infomation' => 'public/users#update'
get '/public/users/infomation' => 'public/users#reload'
get '/public/users/unsubscribe' => 'public/users#unsubscribe'
get '/users' => 'public/users#register'




###admin###

#会員一覧
get 'admin/users' => 'admin/users#index'
get 'admin/users/:id' => 'admin/users#show', as: :admin_users_show
get 'admin/users/:id/edit' => 'admin/users#edit', as: :admin_users_edit
patch '/admin/users/:id' => 'admin/users#update', as: :admin_users_update
delete '/admin/users/:id' => 'admin/users#destroy', as: :admin_users_destroy

#サウナ情報
patch '/admin/saunas/:id' => 'admin/saunas#update', as: :admin_saunas_update
get '/admin/saunas' => 'admin/saunas#index'
get '/admin/saunas/new' => 'admin/saunas#new', as: :admin_saunas_new
post '/admin/saunas' => 'admin/saunas#create', as: :admin_saunas_create
get '/admin/saunas/search' => 'admin/saunas#search'
get '/admin/saunas/result' => 'admin/saunas#result'
get '/admin/saunas/:id' => 'admin/saunas#show', as: :admin_saunas_show
get '/admin/saunas/:id/edit' => 'admin/saunas#edit', as: :admin_saunas_edit
delete '/admin/saunas/:id' => 'admin/saunas#destroy', as: :admin_saunas_destroy


#レビュー
get '/admin/:sauna_id/reviews/' => 'admin/reviews#index', as: :admin_reviews_index
delete '/admin/:sauna_id/reviews/:id' => 'admin/reviews#destroy', as: :admin_reviews_destroy

#コメント機能
get '/admin/:review_id/comments/' => 'admin/comments#index', as: :admin_comments_index
get '/admin/:review_id/comments/:id' => 'admin/comments#show', as: :admin_comments_show
delete '/admin/:review_id/comments/:id' => 'admin/comments#destroy', as: :admin_comments_destroy


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/sauna.rb
class Sauna < ApplicationRecord
    
    geocoded_by :address
    after_validation :geocode, if: :address_changed?
    
    has_many :reviews, dependent: :destroy
    
    #都道府県での検索ツール
    include JpPrefecture
    
    #都道府県のID
    enum prefecture:{
     "---":0,
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46, 
     沖縄県:47
   }

    
     def self.ransackable_attributes(auth_object = nil)
    ["address", "business_hour", "created_at", "id", "latitude", "longitude", "name", "prefecture", "price", "room_temperature", "updated_at",
    "water_temperature", ]
     end
     
     def self.ransackable_associations(auth_object = nil)
    ["image_attachment", "image_blob", "reviews"]
     end
    
    
    #画像
    has_one_attached :image
    
    validates :name, presence: true
    validates :image, presence: true
    validates :price, presence: true
    validates :business_hour, presence: true
    validates :room_temperature, presence: true
    validates :water_temperature, presence: true
    validates :prefecture, presence: true
    validates :address, presence: true
end

app/controllers/admin/saunas_controller.rb
class Admin::SaunasController < ApplicationController
    before_action :authenticate_admin!
    
    def index
        @saunas = Sauna.page(params[:page]).per(10)
    end
    
    def new
        @sauna = Sauna.new  
    end
    
    
    def create
        @sauna = Sauna.new(sauna_params)
        if @sauna.save
           redirect_to  admin_saunas_show_path(@sauna)
        else
           redirect_to request.referer
        end
    end
    
    def show
        @sauna = Sauna.find(params[:id])
    end
    
    
    def edit
        @sauna = Sauna.find(params[:id])
    end
    
    def update
        sauna = Sauna.find(params[:id])
        if sauna.update(sauna_params)
           redirect_to admin_saunas_show_path
        else
           redirect_to request.referer
        end
    end
    
    def destroy
        sauna = Sauna.find(params[:id])
        sauna.destroy
        redirect_to admin_saunas_path
    end
    
    def search
        @q = Sauna.ransack(params[:q])
    end
    
    def result
       @q = Sauna.ransack(params[:q])
       @results = @q.result
    end
    
    private
  def sauna_params
    params.require(:sauna).permit(:name, :price, :business_hour, :room_temperature, :water_temperature, :prefecture, 
    :address, :latitude, :longitude, :image)
  end
end

app/helpers/admin/saunas_helper.rb
module Admin::SaunasHelper
end

app/views/admin/saunas/edit.html.erb
<div class="container">
    <div class="text-center"><br>
         <h1><%= @sauna.name %>の情報を編集する</h1>
         <%= form_with model: @sauna, url: admin_saunas_update_path, method: :patch do |f| %>
         <div class="text-left">
         <table class="table">
             <tbody>
                 <tr>
                     <td>店名</td>
                     <td><%= f.text_field :name %></td>
                 </tr>
                 <tr>
                     <td>イメージ画像</td>
                     <td> <%= f.file_field :image, accept: "image/*" %></td>
                 </tr>
                 <tr>
                     <td>入浴料</td>
                     <td><%= f.text_field :price %>円</td>
                 </tr>
                 <tr>
                     <td>営業時間(〇〇:〇〇〜〇〇:〇〇)</td>
                     <td><%= f.text_field :business_hour %></td>
                 </tr>
                 <tr>
                     <td>サウナの室内温度</td>
                     <td><%= f.text_field :room_temperature %>℃</td>
                 </tr>
                 <tr>
                     <td>水風呂の温度</td>
                     <td><%= f.text_field :water_temperature %>℃</td>
                 </tr>
                 <tr>
                     <td>都道府県</td>
                     <td><%= f.select :prefecture, Sauna.prefectures.keys, {}, {class: 'hoge'} %></td>
                 </tr>
                 <tr>
                     <td>住所</td>
                     <td><%= f.text_field :address %></td>
                 </tr>
                 <tr>
                     <td><%= f.submit '保存', class: "btn btn-success" %></td>
                     <td><%= link_to "削除", admin_saunas_destroy_path(@sauna), method: :delete, class: "btn btn-danger" %></td>
                 </tr>
             </tbody>
         </table>
         </div>
         <% end %>
    </div>
</div>

app/views/admin/saunas/index.html.erb
<div class="container">
    <div class="text-center"><br>
        <h1>全国のサウナ一覧</h1>
        <div class ="text-right">
            <%= link_to "サウナを登録する", admin_saunas_new_path, class: "fa-solid fa-pen-nib" %>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <td>イメージ画像</td>
                    <td>店名</td>
                    <td>料金</td>
                    <td>営業時間</td>
                    <td>都道府県</td>
                    <td>住所</td>
                    <td>レビュー</td>
                    <td>レビュー評価(平均値)</td>
                </tr>
            </thead>
            <% @saunas.each do |sauna| %>
            <tbody>
                <tr>
                    <td><% if sauna.image.attached? %>
                          <%= image_tag sauna.image, size: "80x80" %>
                        <% end %>
                    </td>
                    <td><%= link_to sauna.name, admin_saunas_show_path(sauna) %></td>
                    <td><%= sauna.price %>円</td>
                    <td><%= sauna.business_hour %></td>
                    <td><%= sauna.prefecture %></td>
                    <td><%= sauna.address %></td>
                    <td><%= link_to "#{sauna.reviews.count}件", admin_reviews_index_path(sauna.id) %></td>
                    <td><div id="review_star<%= sauna.id %>"></div><%= number_with_precision(sauna.reviews.average(:star), precision: 1) %></td>
                </tr>
            </tbody>
            <script>
            $(document).on('turbolinks:load', function() {
               let elem = document.querySelector('#review_star<%= sauna.id %>');
                 if (elem == null) return;
                   elem.innerHTML = "";
               let opt = {  
               starOn: "<%= asset_path('star-on.png') %>",
               starOff: "<%= asset_path('star-off.png') %>",
               starHalf: '<%= asset_path('star-half.png') %>',
               score: <%= sauna.reviews.average(:star).to_f.round(1) %>,
               readOnly: true,
               };
             raty(elem, opt);
            });
          </script>
            <% end %>
        </table>
        <div class="col-3 ml-2 mx-auto">
            <%= paginate @saunas, theme: 'twitter-bootstrap-4' %>
        </div>
    </div>
</div>




        

app/views/admin/saunas/new.html.erb
<div class="container">
    <div class="text-left"><br>
        <h1>新規店舗情報を投稿する</h1>
        <p>画像項目も含め、入力は必須です</p>
        <%= form_with model: @sauna, url: admin_saunas_create_path, method: :post do |f| %>
        <table class="table">
            <tr>
                <td>店名</td>
                <td><%= f.text_field :name %></td>
            </tr>
            <tr>
                <td>店のイメージ</td>
                <td><%= f.file_field :image, accept: "image/*" %></td>
            </tr>
            <tr>
                <td>入浴料</td>
                <td><%= f.text_field :price %>円</td>
            </tr>
            <tr>
                <td>営業時間(〇〇:〇〇〜〇〇:〇〇)</td>
                <td><%= f.text_field :business_hour %></td>
            </tr>
            <tr>
                <td>サウナの室内温度</td>
                <td><%= f.text_field :room_temperature %>℃</td>
            </tr>
            <tr>
                <td>水風呂の温度</td>
                <td><%= f.text_field :water_temperature %>℃</td>
            </tr>
            <tr>
                <td>都道府県</td>
                <td><%= f.select :prefecture, Sauna.prefectures.keys, {}, {class: 'hoge'} %></td>
            </tr>
            <tr>
                <td>住所</td>
                <td><%= f.text_field :address %></td>
                <td><%= f.submit '作成する', class: "btn btn-success" %></td>
            </tr>
        </table>
        <% end %>
    </div>
</div>

app/views/admin/saunas/result.html.erb
<div class="container">
    <div class="text-center">
        <h1><%= @results.first&.prefecture %>のサウナ一覧</h1>
        <table class="table">
            <thead>
            <tr>
                <td>お店の画像</td>
                <td>店名</td>
                <td>入浴料</td>
                <td>都道府県</td>
                <td>住所</td>
                <td>レビュー件数</td>
                <td>レビュー評価(平均値)</td>
            </tr>
            </thead>
            <% @results.each do |sauna| %>
            <tbody>
                <tr>
                    <td><% if sauna.image.attached? %>
                          <%= image_tag sauna.image, size: "80x80" %>
                        <% else %>
                          <%= image_tag 'no_image', size: "80x80" %>
                        <% end %>
                    </td>
                    <td><%= link_to sauna.name, admin_saunas_show_path(sauna) %></td>
                    <td><%= sauna.price %>円</td>
                    <td><%= sauna.prefecture %></td>
                    <td><%= sauna.address %></td>
                    <td><%= link_to "#{sauna.reviews.count}件", admin_reviews_index_path(sauna.id) %></td>
                    <td><div id="review_star<%= sauna.id %>"></div><%= number_with_precision(sauna.reviews.average(:star), precision: 1) %></td>
                </tr>
            </tbody>
            <script>
            $(document).on('turbolinks:load', function() {
               let elem = document.querySelector('#review_star<%= sauna.id %>');
                 if (elem == null) return;
                   elem.innerHTML = "";
               let opt = {  
               starOn: "<%= asset_path('star-on.png') %>",
               starOff: "<%= asset_path('star-off.png') %>",
               starHalf: '<%= asset_path('star-half.png') %>',
               score: <%= sauna.reviews.average(:star).to_f.round(1) %>,
               readOnly: true,
               };
             raty(elem, opt);
            });
          </script>
            <% end %>
        </table>
    </div>
</div>

app/views/admin/saunas/search.html.erb
<div class="container">
  <div class="text-center"><br>
    <h2>検索画面</h2>
         <p>この画面では都道府県ごとにサウナをお調べいただけます。</p>
         <p>お近くの都道府県でのお調べや、</p>
         <p>気になった都道府県でのお調べにご活用ください。</p>
       <%= search_form_for(@q, url: admin_saunas_result_path) do |f| %>
          <%= f.collection_select :prefecture_eq, JpPrefecture::Prefecture.all, :code, :name, class: 'form-control' %>
          <%= f.submit "検索", class: "btn btn-primary" %>
       <% end %>
  </div>
</div>


  

app/views/admin/saunas/show.html.erb
<div class="container">
  <div class="text-center"><br>
      <h1><%= @sauna.name %>の詳細ページ</h1>
      <table class="table">
        <tbody>
          <tr>
            <td>店名</td>
            <td><%= @sauna.name %></td>
          </tr>
          <tr>
            <td>店の外観</td>
            <td><% if @sauna.image.attached? %>
                  <%= image_tag @sauna.image, size: "300x300" %>
                <% else %>
                  <%= image_tag 'no_image', size: "300x300" %>
                <% end %>
            </td>
          </tr>
          <tr>
            <td>入浴料</td>
            <td><%= @sauna.price %>円</td>
          </tr>
          <tr>
            <td>営業時間</td>
            <td><%= @sauna.business_hour %></td>
          </tr>
          <tr>
            <td>サウナの室内温度</td>
            <td><%= @sauna.room_temperature %>℃</td>
          </tr>
          <tr>
            <td>水風呂の温度</td>
            <td><%= @sauna.water_temperature %>℃</td>
          </tr>
          <tr>
            <td>都道府県</td>
            <td><%= @sauna.prefecture %></td>
          </tr>
          <tr>
            <td>住所</td>
            <td><%= @sauna.address %></td>
          </tr>
          <tr>
            <td></td>
            <td><%= link_to "編集", admin_saunas_edit_path, class: "btn btn-success" %></td>
          </tr>
        </tbody>
      </table>
  </div>
</div>