config/routes.rb
Rails.application.routes.draw do
  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  
}
devise_scope :user do
  post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
end
 devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


root to: "public/homes#top"
get 'about' => 'public/homes#about'

###public###

#サウナ情報
get '/public/saunas' => 'public/saunas#index' 
get '/public/saunas/:id/map' => 'public/saunas#map', as: :public_saunas_map
get '/public/saunas/search' => 'public/saunas#search', as: :public_saunas_search
get '/public/saunas/result' => 'public/saunas#result', as: :public_saunas_result
get '/public/saunas/:id' => 'public/saunas#show', as: :public_saunas_show

#レビュー
get '/public/saunas/:sauna_id/reviews' => 'public/reviews#index', as: :public_sauna_reviews
get '/public/saunas/:sauna_id/reviews/new' => 'public/reviews#new', as: :new_public_sauna_review
post '/public/saunas/:sauna_id/reviews' => 'public/reviews#create', as: :public_sauna_reviews_create
get '/public/saunas/:sauna_id/reviews/:id/edit' => 'public/reviews#edit', as: :edit_public_sauna_review
patch '/public/saunas/:sauna_id/reviews/:id' => 'public/reviews#update', as: :public_sauna_review_update
delete '/public/saunas/:sauna_id/reviews/:id' => 'public/reviews#destroy', as: :public_sauna_review_destroy

#コメント
post '/public/:review_id/comments' => 'public/comments#create', as: :public_comments_create
get '/public/:review_id/comments/:id' => 'public/comments#show', as: :public_comments_show
get '/public/:review_id/comments/:id/edit' => 'public/comments#edit', as: :public_comments_edit
get '/public/:review_id/comments/' => 'public/comments#reload'
patch '/public/:review_id/comments/:id' => 'public/comments#update', as: :public_comments_update
delete '/public/:review_id/comments/:id' => 'public/comments#destroy',as: :public_comments_destroy




#マイページ
delete '/public/users/destroy' => 'public/users#destroy'
get '/public/users/my_page' => 'public/users#show'
get '/public/users/infomation/edit' => 'public/users#edit'
patch '/public/users/infomation' => 'public/users#update'
get '/public/users/infomation' => 'public/users#reload'
get '/public/users/unsubscribe' => 'public/users#unsubscribe'
get '/users' => 'public/users#register'




###admin###

#会員一覧
get 'admin/users' => 'admin/users#index'
get 'admin/users/:id' => 'admin/users#show', as: :admin_users_show
get 'admin/users/:id/edit' => 'admin/users#edit', as: :admin_users_edit
patch '/admin/users/:id' => 'admin/users#update', as: :admin_users_update
delete '/admin/users/:id' => 'admin/users#destroy', as: :admin_users_destroy

#サウナ情報
patch '/admin/saunas/:id' => 'admin/saunas#update', as: :admin_saunas_update
get '/admin/saunas' => 'admin/saunas#index'
get '/admin/saunas/new' => 'admin/saunas#new', as: :admin_saunas_new
post '/admin/saunas' => 'admin/saunas#create', as: :admin_saunas_create
get '/admin/saunas/search' => 'admin/saunas#search'
get '/admin/saunas/result' => 'admin/saunas#result'
get '/admin/saunas/:id' => 'admin/saunas#show', as: :admin_saunas_show
get '/admin/saunas/:id/edit' => 'admin/saunas#edit', as: :admin_saunas_edit
delete '/admin/saunas/:id' => 'admin/saunas#destroy', as: :admin_saunas_destroy


#レビュー
get '/admin/:sauna_id/reviews/' => 'admin/reviews#index', as: :admin_reviews_index
delete '/admin/:sauna_id/reviews/:id' => 'admin/reviews#destroy', as: :admin_reviews_destroy

#コメント機能
get '/admin/:review_id/comments/' => 'admin/comments#index', as: :admin_comments_index
get '/admin/:review_id/comments/:id' => 'admin/comments#show', as: :admin_comments_show
delete '/admin/:review_id/comments/:id' => 'admin/comments#destroy', as: :admin_comments_destroy


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
         
         
    has_many :reviews, dependent: :destroy
    has_many :comments, dependent: :destroy
         
         validates :first_name, presence: true
         validates :last_name, presence: true
         validates :first_name_kana, presence: true
         validates :last_name_kana, presence: true
         validates :postcode, presence: true
         validates :address, presence: true
         validates :telephone_number, presence: true
         validates :birthday, presence: true
         
         
   
    
    
    
    def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.last_name = "ゲスト"
      user.first_name = "ネーム"
      user.last_name_kana = "ゲスト"
      user.first_name_kana = "ネーム"
      user.postcode = "ゲスト住所"
      user.address = "ゲスト住所"
      user.telephone_number = "000-0000-0000"
      user.birthday = "1900年01年01日"
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
    end
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
     before_action :authenticate_admin!
    
    
    def index
        @users = User.page(params[:page]).per(10)
        @user = User.all
    end
    
    def show
        @user = User.find(params[:id])
    end
    
    def edit
        @user = User.find(params[:id])
        if @user.email == "guest@example.com"
           render :show
        end
    end
    
    def update
        user = User.find(params[:id])
        if user.email == "guest@example.com"
           render :show
        else
          user.update(user_params)
          redirect_to admin_users_show_path
        end
    end
    
    def destroy
        user = User.find(params[:id])
        user.destroy
        redirect_to admin_users_path 
    end
    
    
     private
  def user_params
    params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postcode, :address,
     :telephone_number, :birthday, :email)
  end
    
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
    <div class="text-center">
         <h1><%= @user.last_name + @user.first_name %>さんの情報を編集する</h1>
         <%= form_with model: @user, url: admin_users_update_path, method: :patch do |f| %>
         <table class="table">
             <tbody>
                 <tr>
                     <td>名前</td>
                     <td><%= f.text_field :last_name %></td>
                     <td><%= f.text_field :first_name %></td>
                 </tr>
                 <tr>
                     <td>フリガナ</td>
                     <td><%= f.text_field :last_name_kana %></td>
                     <td><%= f.text_field :first_name_kana %></td>
                 </tr>
                 <tr>
                     <td>郵便番号</td>
                     <td><%= f.text_field :postcode %></td>
                 </tr>
                 <tr>
                     <td>住所</td>
                     <td><%= f.text_field :address %></td>
                 </tr>
                 <tr>
                     <td>電話番号</td>
                     <td><%= f.text_field :telephone_number %></td>
                 </tr>
                 <tr>
                     <td>生年月日</td>
                     <td><%= f.text_field :birthday %></td>
                 </tr>
                 <tr>
                     <td>メールアドレス</td>
                     <td><%= f.text_field :email %></td>
                 </tr>
                 <tr>
                     <td></td>
                     <td><%= f.submit '保存', class: "btn btn-success" %></td>
                     <td><%= link_to "削除する", admin_users_destroy_path(@user), method: :delete, class: "btn btn-danger" %></td>
                 </tr>
             </tbody>
         </table>
         <% end %>
    </div>
</div>


 

app/views/admin/users/index.html.erb
<div class="container">
    <div class="text-center"><br>
        <h1>会員一覧</h1>
        <table class="table">
            <div class="text-right">
                <p>Total：<%= @user.count %>名様</p>
            </div>
            <thead>
                <tr class="table-active">
                    <td><b>会員ID</b></td>
                    <td><b>氏名</b></td>
                    <td><b>メールアドレス</b></td>
                </tr>
            </thead>
            <% @users.each do |user| %>
            <tbody>
                <tr>
                    <td><%= user.id %></td>
                    <td><%= link_to user.last_name + user.first_name, admin_users_show_path(user) %>
                    <td><%= user.email %></td>
                </tr>
            </tbody>
            <% end %>
        </table>
    </div>
    <div class="col-3 ml-2 mx-auto">
        <%= paginate @users, theme: 'twitter-bootstrap-4' %>
    </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
    <div class="text-center"><br>
         <h1><%= @user.last_name + @user.first_name %>さんの詳細画面</h1>
         <table class="table">
             <tbody>
                 <tr>
                     <td>名前</td>
                     <td><%= @user.last_name + @user.first_name %></td>
                 </tr>
                 <tr>
                     <td>フリガナ</td>
                     <td><%= @user.last_name_kana + @user.first_name_kana %></td>
                 </tr>
                 <tr>
                     <td>郵便番号</td>
                     <td><%= @user.postcode %></td>
                 </tr>
                 <tr>
                     <td>住所</td>
                     <td><%= @user.address %></td>
                 </tr>
                 <tr>
                     <td>電話番号</td>
                     <td><%= @user.telephone_number %></td>
                 </tr>
                 <tr>
                     <td>生年月日</td>
                     <td><%= @user.birthday %></td>
                 </tr>
                 <tr>
                     <td>メールアドレス</td>
                     <td><%= @user.email %></td>
                 </tr>
                 <tr>
                     <td>
                         <% if @user.email == 'guest@example.com' %>
                            <p class="text-danger">ゲストユーザーはユーザー情報の編集ができません。</p>
                         <% else %>
                            <%= link_to "編集する", admin_users_edit_path(@user), class: "btn btn-success" %>
                         <% end %>
                     </td>
                     <td></td>
                 </tr>
             </tbody>
         </table>
    </div>
</div>