config/routes.rb
Rails.application.routes.draw do
  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  
}
devise_scope :user do
  post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
end
 devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}


root to: "public/homes#top"
get 'about' => 'public/homes#about'

###public###

#サウナ情報
get '/public/saunas' => 'public/saunas#index' 
get '/public/saunas/:id/map' => 'public/saunas#map', as: :public_saunas_map
get '/public/saunas/search' => 'public/saunas#search', as: :public_saunas_search
get '/public/saunas/result' => 'public/saunas#result', as: :public_saunas_result
get '/public/saunas/:id' => 'public/saunas#show', as: :public_saunas_show

#レビュー
get '/public/saunas/:sauna_id/reviews' => 'public/reviews#index', as: :public_sauna_reviews
get '/public/saunas/:sauna_id/reviews/new' => 'public/reviews#new', as: :new_public_sauna_review
post '/public/saunas/:sauna_id/reviews' => 'public/reviews#create', as: :public_sauna_reviews_create
get '/public/saunas/:sauna_id/reviews/:id/edit' => 'public/reviews#edit', as: :edit_public_sauna_review
patch '/public/saunas/:sauna_id/reviews/:id' => 'public/reviews#update', as: :public_sauna_review_update
delete '/public/saunas/:sauna_id/reviews/:id' => 'public/reviews#destroy', as: :public_sauna_review_destroy

#コメント
post '/public/:review_id/comments' => 'public/comments#create', as: :public_comments_create
get '/public/:review_id/comments/:id' => 'public/comments#show', as: :public_comments_show
get '/public/:review_id/comments/:id/edit' => 'public/comments#edit', as: :public_comments_edit
get '/public/:review_id/comments/' => 'public/comments#reload'
patch '/public/:review_id/comments/:id' => 'public/comments#update', as: :public_comments_update
delete '/public/:review_id/comments/:id' => 'public/comments#destroy',as: :public_comments_destroy




#マイページ
delete '/public/users/destroy' => 'public/users#destroy'
get '/public/users/my_page' => 'public/users#show'
get '/public/users/infomation/edit' => 'public/users#edit'
patch '/public/users/infomation' => 'public/users#update'
get '/public/users/infomation' => 'public/users#reload'
get '/public/users/unsubscribe' => 'public/users#unsubscribe'
get '/users' => 'public/users#register'




###admin###

#会員一覧
get 'admin/users' => 'admin/users#index'
get 'admin/users/:id' => 'admin/users#show', as: :admin_users_show
get 'admin/users/:id/edit' => 'admin/users#edit', as: :admin_users_edit
patch '/admin/users/:id' => 'admin/users#update', as: :admin_users_update
delete '/admin/users/:id' => 'admin/users#destroy', as: :admin_users_destroy

#サウナ情報
patch '/admin/saunas/:id' => 'admin/saunas#update', as: :admin_saunas_update
get '/admin/saunas' => 'admin/saunas#index'
get '/admin/saunas/new' => 'admin/saunas#new', as: :admin_saunas_new
post '/admin/saunas' => 'admin/saunas#create', as: :admin_saunas_create
get '/admin/saunas/search' => 'admin/saunas#search'
get '/admin/saunas/result' => 'admin/saunas#result'
get '/admin/saunas/:id' => 'admin/saunas#show', as: :admin_saunas_show
get '/admin/saunas/:id/edit' => 'admin/saunas#edit', as: :admin_saunas_edit
delete '/admin/saunas/:id' => 'admin/saunas#destroy', as: :admin_saunas_destroy


#レビュー
get '/admin/:sauna_id/reviews/' => 'admin/reviews#index', as: :admin_reviews_index
delete '/admin/:sauna_id/reviews/:id' => 'admin/reviews#destroy', as: :admin_reviews_destroy

#コメント機能
get '/admin/:review_id/comments/' => 'admin/comments#index', as: :admin_comments_index
get '/admin/:review_id/comments/:id' => 'admin/comments#show', as: :admin_comments_show
delete '/admin/:review_id/comments/:id' => 'admin/comments#destroy', as: :admin_comments_destroy


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
      <h2 class="collapse navbar-collapse justify-content-center">
        <a href="/" ><img class="card-img" src="<%= asset_path('logo.jpg') %>" style="height: 100px; width: 100%;" /></a>
</nav>
<div class="text-right bg-light">
      <% if user_signed_in? %>
        <%= current_user.last_name + current_user.first_name %>さんようこそ
      <% end %>
</div>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "マイページ", public_users_my_page_path, class: "nav-link active fa-solid fa-user-pen" %>
        </li>
        <li class="nav-item">
          <%= link_to "全国のサウナ一覧",  public_saunas_path, class: "nav-link active fa-sharp fa-solid fa-fire" %>
        </li>
        <li class="nav-item">
          <%= link_to "サウナを検索する", public_saunas_search_path, class: "nav-link active fa-solid fa-magnifying-glass" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link active fa-solid fa-right-from-bracket" %>
        </li>
        <% elsif admin_signed_in? %>
        <li class="nav-item">
          <%= link_to "会員一覧", admin_users_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "全国のサウナ一覧", admin_saunas_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "サウナを検索する", admin_saunas_search_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link active" %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link active fa-brands fa-hotjar" %>
        </li>
        <li class="nav-item">
          <%= link_to 'ゲストログイン', users_guest_sign_in_path, method: :post, class: "nav-link active fa-solid fa-circle-user" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログイン", new_user_session_path, class: "nav-link active fa-solid fa-right-to-bracket" %>
        </li>
        <li class="nav-item">
          <%= link_to "新規登録", new_user_registration_path, class: "nav-link active fa-solid fa-file-signature" %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>極めろ！サウナ道</title>
    
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://kit.fontawesome.com/e70b314ceb.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('logo.jpg') %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>